version: '3.9'

services:
  db:
    image: 'postgres'
    ports:
      - '2345:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'labpro'
  server:
    build: .
    ports:
      - '5000:5000'
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@db:5432/labpro?schema=public'
      ACCESS_TOKEN_SECRET: 'access-token-secret'
      API_KEY_EXCHANGE_RATE: '0aLK13jw0zp0hjE0wZ9rJSzvxDKpcIzA'
